export const data = [
  {
    id: 1,
    name: 'Smartphone',
    description: 'High-performance smartphone with advanced features',
    price: 599.99,
    quantity: 50,
  },
  {
    id: 2,
    name: 'Laptop',
    description: 'Thin and lightweight laptop for productivity',
    price: 899.50,
    quantity: 30,
  },
  {
    id: 3,
    name: 'Headphones',
    description: 'Wireless noise-cancelling headphones for immersive sound',
    price: 149.99,
    quantity: 100,
  },
  {
    id: 4,
    name: 'Smartwatch',
    description: 'Fitness tracker with heart rate monitor and GPS',
    price: 199.00,
    quantity: 40,
  },
  {
    id: 5,
    name: 'Camera',
    description: 'High-resolution digital camera for professional photography',
    price: 699.75,
    quantity: 20,
  },
  {
    id: 6,
    name: 'Tablet',
    description: 'Portable tablet with a large screen for entertainment',
    price: 349.49,
    quantity: 60,
  },
  {
    id: 7,
    name: 'Wireless Speaker',
    description: 'Portable speaker with Bluetooth connectivity',
    price: 79.99,
    quantity: 80,
  },
  {
    id: 8,
    name: 'Gaming Console',
    description: 'Powerful gaming console for an immersive gaming experience',
    price: 449.00,
    quantity: 25,
  },
  {
    id: 9,
    name: 'External Hard Drive',
    description: 'High-capacity external hard drive for data storage',
    price: 129.95,
    quantity: 35,
  },
  {
    id: 10,
    name: 'Fitness Tracker',
    description: 'Wearable fitness tracker with activity monitoring features',
    price: 89.50,
    quantity: 70,
  },
];
